{% set name = "expandsets" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source: 
  path: ../src

requirements:
  host:
    - python>=3
  run:
    - python>=3

about:
  home: https://github.com/bidauxpoto/expandsets.git
  summary: 
